---
title: "Rescue Mission"
type: "challenge"
description: "Build a website like stackoverflow.com for posting questions and answers."
depends: "meetups-in-space"
visibility: "assign"
ignore:
- "rescue-mission.md"
